http://localhost:5000/api/compounds

###
http://localhost:5000/api/compounds/9db8271b-572d-4223-8c60-d619e2bdf21f

###
PATCH http://localhost:5000/api/compounds/6e2f584b-2dec-4ca0-b142-ea82871f4b79

    {
    "uid": "6e2f584b-2dec-4ca0-b142-ea82871f4b79",
    "name": "Boron",
    "document": true,
    "aqueous_props": "Boric acid (pKa=9.3)",
    "adsorption_props": "Chelating resins",
    "analytical_techniques": "ICP",
    "spectroscopic_techniques": "XAS SAX",
    "experiments": [
        {
            "type": "XAS",
            "researcher": "Trillian Astra",
            "date": "2018-04-23",
            "run": "4a4045f6-bbb5-4c48-ac29-d504fd3fa266"
        },
        {
            "type": "XAS",
            "researcher": "Trillian Astra",
            "date": "2018-04-24",
            "run": "bed0b2c3-a1f6-44dc-abf0-a7b0dbfa3219"
        },
        {
            "type": "XAS",
            "researcher": "Zaphod Beeblebrox",
            "date": "2018-04-25",
            "run": "4a4045f6-bbb5-4c48-ac29-d504fd3fa266"
        },
        {
            "type": "XAS",
            "researcher": "Zaphod Beeblebrox",
            "date": "2018-04-26",
            "run": "bed0b2c3-a1f6-44dc-abf0-a7b0dbfa3219"
        }
    ]
    }

###
POST http://localhost:5000/api/compounds HTTP/1.1
content-type: application/json

   {
    "name": "Boron",
    "document": true,
    "aqueous_props": "Boric acid (pKa=9.3)",
    "adsorption_props": "Chelating resins",
    "analytical_techniques": "ICP",
    "spectroscopic_techniques": "XAS SAX",
    "experiments": [
         {
            "type": "XAS",
            "researcher": "Trillian Astra",
            "date": "2018-04-23",
            "run": "4a4045f6-bbb5-4c48-ac29-d504fd3fa266"
        },
        {
            "type": "XAS",
            "researcher": "Trillian Astra",
            "date": "2018-04-24",
            "run": "4a4045f6-bbb5-4c48-ac29-d504fd3fa266"
        }
    ]
    }
###
DELETE http://localhost:5000/api/compounds/5c917b907524073330b468a45c916f7075240728ed4287d4 HTTP/1.1

object